### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by autumngreenbean** [autumngreenbean/resume#1]
Website is no longer working after simple push/pull changes from and to the repository. Mainly work with index.html
Attempted to refresh the directory path of the repository with no avail.  
Build appears to be stable, but deployment is delayed by status code 200 error!
Attempted to rebuild 3x

**Comment by autumngreenbean** [comment]
Going to fork the repository and refer to the following guide: [Error 209](https://github.com/alshedivat/al-folio/issues/209#issuecomment-798849211)

**Comment by autumngreenbean** [comment]
Issue persists. Will attempt to revert to old version of repository.

**Comment by prcr** [comment]
This is just to let you know that I found this issue because I'm having the same problem with the deployment to GitHub pages on this repository:

https://github.com/codacy/docs/actions/workflows/pages/pages-build-deployment

It's probably an issue on the GitHub side, but I can't find any info on it. I'll let you know if I can find a solution to this.

**Edit:** I found this thread where more people are complaining about the same issue, so it definitely looks like something that must be fixed by GitHub: https://github.com/orgs/community/discussions/39907

**Comment by autumngreenbean** [comment]
Thank you for contacting me!

If you do find a solution I would appreciate the guidance immensely.
________________________________

**Comment by autumngreenbean** [comment]
I'm glad that it wasn't anything on my side causing the problem. I'll attempt to re-deploy as it looks like the issue should be cleared up  on the Github side. Thank you for being so informative!

**Comment by prcr** [comment]
Yes, a redeploy seems to be enough to fix the issue now. I'm glad I could help!
